### PR TITLE
added real time password strength checker

### LINKED ISSUE #68: [FEATURE]  Real time password strength Checker
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

@10kumaranurag01 We can implement password strength checker for the user it will provide the user better user experience with UI .When user will add complex letter in it's password then it will tell him accordingly ,if user will add simple letter then it will also suggest

### Proposed Solution

When user will add complex letter in it's password then it will tell him accordingly ,if user will add simple letter then it will also suggest.
Kindly assign e this issue and label as Hacktoberfest
A demo video i have attached here

### Screenshots

https://github.com/user-attachments/assets/e9c2d218-2ff0-4fb9-b16f-9853d5b0ce32

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will check what is the user input lowercase or uppercase or any special character

### PR DESCRIPTION
**Pull request by agnijeetsharma**
## Fixes Issue

closes #68

## Changes proposed

I have implemented real time password strength checker

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.   ---done
- [ ] My change requires changes to the documentation. 
- [x ] I have updated the documentation accordingly.       ---done
- [x ] All new and existing tests passed.         --done
- [ x] This PR does not contain plagiarized content.         --done
- [ x] The title of my pull request is a short description of the requested changes. --done

## Screenshots
I have attached video of the changes

https://github.com/user-attachments/assets/7bb49e79-d7f8-442c-8b1e-b6df3a942950

## Note to reviewers

@10kumaranurag01 Kindly merge my PR under hacktoberfest

### CODE REVIEW

**Comment by 10kumaranurag01** [comment]
@agnijeetsharma Make the first letter of the strengths to upper case.

**Comment by agnijeetsharma** [comment]
@10kumaranurag01 Done

Kindly label as hacktoberfest and hacktoberfest-accepted

**Comment by agnijeetsharma** [comment]
Screenshot 2024-10-14 102429

**Comment by 10kumaranurag01** [comment]
Can you add a hide/unhide toggle in password input box?

**Comment by agnijeetsharma** [comment]
@10kumaranurag01  I think there might be mess up if i change more thing so Kindly merge first this branch ,for hide/unhide i will request another PR

**Pull request merged**
