### PR TITLE
Sidebar Improvement.

### PR DESCRIPTION
**Pull request by Krishna3451**
## Fixes Issue
The selected section in the sidebar is darker to visually indicate that it is currently active.

### CODE REVIEW

**Comment by 10kumaranurag01** [comment]
@Krishna3451 Can you post any screenshot of both selected and not selected?

**Comment by 10kumaranurag01** [comment]
@Krishna3451 Also do these changes to the mobile nav.

**Comment by Krishna3451** [comment]
@10kumaranurag01 
Screenshot 2024-10-08 233127
Screenshot 2024-10-08 233143


Works on mobile too.

**Comment by 10kumaranurag01** [comment]
@Krishna3451 How does it look in dark mode?

**Comment by 10kumaranurag01** [comment]
image
 
@Krishna3451 And use this gray color for unselected page.

**Comment by Krishna3451** [comment]
@10kumaranurag01 
In Dark Mode
Screenshot 2024-10-09 000535
Screenshot 2024-10-09 000544

**Comment by 10kumaranurag01** [comment]
In dark mode the selected one should be white and the unselected one should be gray. And remember to use the same gray color as below iimage.

image

**Comment by Krishna3451** [comment]
@10kumaranurag01 
Does this looks good.
image

**Comment by Krishna3451** [comment]
@10kumaranurag01 Could you please specify how you would like the fonts to appear?

**Comment by 10kumaranurag01** [comment]
@Krishna3451 In dark mode the selected one should have white background with black text and unselected one should have gray background with white text

In light mode, the selected one should have gray background with white text and unselected one should have white background with black text

**Comment by Krishna3451** [comment]
@10kumaranurag01 Fixed the font colors, for both desktop and mobile.
Screenshot 2024-10-09 102448
Screenshot 2024-10-09 102456
Screenshot 2024-10-09 102529

**Comment by Krishna3451** [comment]
@10kumaranurag01 Any update?

**Pull request merged**
