### PR TITLE
updated AddEditTodoDialog.js

### PR DESCRIPTION
**Pull request by Abhiraj-Sardar**
I Just Updated AddEditTodoDialog.js, to solve the [Issue #1](https://github.com/10kumaranurag01/todo-done/issues/1).

Before Updatation:
image

After Updatation:

https://github.com/user-attachments/assets/59f797eb-b6d6-4a4b-89c6-4c47ec069cd9

### CODE REVIEW

**Comment by 10kumaranurag01** [comment]
@Abhiraj-Sardar  Can you add a todo and give a screen recording that the todos are getting added?

**Comment by Abhiraj-Sardar** [comment]
> @Abhiraj-Sardar Can you add a todo and give a screen recording that the todos are getting added?

@10kumaranurag01  Sure...

I discovered that the Input Fields are not working Properly....
although the issue was 👇

> It first closes dialog and then specify that the fields must not be empty.

This Issue was solved .... but I think You should create a new Issue in this Input Field Blocked so that I can work on it...🤔

**Comment by 10kumaranurag01** [comment]
@Abhiraj-Sardar You can create the issue and i will check it out, make sure to give proper screenshots or screen recordings. In the meanwhile send me the recording of todos getting added successfully from your PR

**Comment by Abhiraj-Sardar** [comment]
> @Abhiraj-Sardar You can create the issue and i will check it out, make sure to give proper screenshots or screen recordings. In the meanwhile send me the recording of todos getting added successfully from your PR

Ok I am Doing The Same....But This Issue is Solved You can review and merge It...So that This Functionality will kept Isolated...from Others.

**Pull request merged**
